### ISSUE TITLE
Session Management should keep the track of all the activities performed in the application.

### ISSUE THREAD

**Issue by Arjunbhavsar** [airavata-courses/scrapbook#124]
All activities should be logged by the session management module.

It should be descriptive enough to tell you all metadata about the image, for example noting the action of deleting the image.
Along with the status of the action -  If image upload is in progress / completed/ failed. 

The session should be a separate module in UI.

**Comment by hrishikeshpaul** [comment]
@Arjunbhavsar yeah we thought about this. We're gonna have the user's timeline, which will have all what that user's done. Currently, the session service just keeps track of which user is in session.

**Comment by Arjunbhavsar** [comment]
@hrishikeshpaul Yes, we need to maintain the user's timeline. you can close the issue after completion.

**Comment by hrishikeshpaul** [comment]
Has been added to the latest commit in main-ui branch
