### ISSUE TITLE
Not able to access the shared Images from Collaborators account.

### ISSUE THREAD

**Issue by Arjunbhavsar** [airavata-courses/scrapbook#125]
Once we upload the image to the Album and share it by adding the collaborator. The collaborator is not able to access the shared image.

**Comment by jbhushan791** [comment]
@Arjunbhavsar : yes, This part is work in progress:  the plan is to have a shared tab, where logged in user as collaborater will be able to see all his collabs.

**Comment by Arjunbhavsar** [comment]
@jbhushan791  Understood. Continue working on it. And Close the issue once completed.

**Comment by jbhushan791** [comment]
Done
