### ISSUE TITLE
Create User Workflow

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#13]
Please review the below user workflow.

![User Workflow](https://user-images.githubusercontent.com/22999894/106673158-2de27580-657f-11eb-923b-80a81d4c1003.png)

@chirag-indi @jbhushan791

**Comment by jbhushan791** [comment]
It looks quite good and entire flow is clear.
It pretty much covers all required activities which I can think of.

**Comment by hrishikeshpaul** [comment]
Adding it to PR #15
