### ISSUE TITLE
Update wiki for Project 1

### ISSUE THREAD

**Issue by chirag-indi** [airavata-courses/scrapbook#14]
# Deliverables

- [x] Readme
- [x] Napkin Diagram
- [x] Workflow & UML
- [x] Mockups
- [x] PR Reviews

**Comment by hrishikeshpaul** [comment]
@chirag-indi hey, I've added the mockups to the repo as a PR #16 

Review it, and then use those to add them (you'll have to use the URL) to the Mockup section in the Wiki

**Comment by chirag-indi** [comment]
I've added a few things to a couple of pages, will do the rest by 6 PM tomorrow.

@hrishikeshpaul @jbhushan791 Do either of you know if a submission template for Milestone 1 was provided? Or do we follow the pattern history looking at old project repositories?

**Comment by hrishikeshpaul** [comment]
@chirag-indi I think there was a slide that had all the things to be submitted. So we'll just follow it and make sure all those points are there in Project 1. 

Nevertheless, we have to make everything look good before the submission. Yeah complete it by 6pm, I'll make rest of the changes!

**Comment by jbhushan791** [comment]
![image](https://user-images.githubusercontent.com/70742367/107127936-b1ee7300-6887-11eb-9c35-c454ab78ea6f.png)


This is the slide for Project 1 Deliverables. Attaching here for reference.
