### ISSUE TITLE
Stress Test Get Albums 

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#189]
These will be tested with 3 replicas first then with 5 replicas. Use JMeter.

**Criteria**,
- 100 users, 100 ramp-up
- 1000 user, 100 ramp-up
- 10000 user, 1000 ramp-up

Use JMeter to do this and post the graphs (along with the throughput, deviation etc).

Steps,
1. Create 5 albums for the user. Upload 10 images in each album.
2. To test, use this URL `http://scrapbook.rocks/api/album?userid=6058d9504d22e80012fcf08f (put your userid here)` [GET]
3. In the header section of requests add, `X-SESSION` -> `<user_id>`

Post results from the `Graph Results`

#### Note: Save the jmx file and upload it in the jmeter branch/folder

**Comment by chirag-indi** [comment]
Completed
