### ISSUE TITLE
Stress Test Get Images

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#190]
These will be tested with 3 replicas first then with 5 replicas. Use JMeter.

**Criteria**,
- 100 users, 100 ramp-up
- 1000 user, 100 ramp-up
- 10000 user, 1000 ramp-up

Use JMeter to do this and post the graphs (along with the throughput, deviation etc).

Steps,
1. To test, use this URL `http://scrapbook.rocks/api/album/14LGye4NAyTL2ZK8UoHOV_t1qR9FpHrhv/image (put your any album googledriveid here)` [GET]
2. 3. In the header section of requests add, `X-SESSION` -> `<user_id>`

Post results from the `Graph Results`

#### Note: Save the jmx file and upload it in the jmeter branch/folder

**Comment by chirag-indi** [comment]
Completed
