### ISSUE TITLE
Create napkin diagram

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#2]

**Comment by jbhushan791** [comment]
![NapkinDiagram](https://user-images.githubusercontent.com/70742367/106951323-a40ce680-66fd-11eb-9805-6a5d503d7476.png)

**Comment by jbhushan791** [comment]
![image](https://user-images.githubusercontent.com/70742367/106951489-d4548500-66fd-11eb-8a85-10999c417c7b.png)

**Comment by jbhushan791** [comment]
<img width="764" alt="NapkinDiagram" src="https://user-images.githubusercontent.com/70742367/106951856-4d53dc80-66fe-11eb-9152-70360c3deb4b.png">


@hrishikeshpaul @chirag-indi  : Please review and let me know if there anything is add/delete from this Napkin diagram. In the meantime, I will look some cool pictures, if I find I will update this diagram.

**Comment by hrishikeshpaul** [comment]
Looks great! I just have 2 comments,
- I think you change the word "Dashboard" to home because when the user logs in they go to their home. 
- I think the metrics could be changed to "Dashboard" instead. 

Let me know what you think. 

Good work!

**Comment by jbhushan791** [comment]
Thanks @hrishikeshpaul ! Will do the necessary changes. Yes I need to find images which are most suitable for Napkin Diagram.

**Comment by hrishikeshpaul** [comment]
Yeah just make it simpler. All the small details aren't required!

**Comment by hrishikeshpaul** [comment]
@chirag-indi @jbhushan791 hey, so I was hanging out with my friend today and was talking about this project. He gave me a brilliant idea that simplifies our napkin diagram. Here's the idea,

![Napkin Diagram](https://user-images.githubusercontent.com/22999894/107107490-4e206780-67ff-11eb-92c7-c58b1d9278af.png)


It feels more like a diagram, and is explanatory. The fact that there are photos of researchers makes it even more evident for our use-case. Please let me know what you think!

**Comment by chirag-indi** [comment]
That looks awesome! I had some free time as well, so tried to make a simplified version. 

![image](https://user-images.githubusercontent.com/20301919/107108088-74e09d00-6803-11eb-84c0-e81129d462e4.png)

I think I like yours better.

**Comment by hrishikeshpaul** [comment]
Oh cool I like yours as well! I think yours depicts our user-case much closely! Its upto you guys what y'all want to work submit!.

**Comment by jbhushan791** [comment]
Wow, I liked both of them. We could pick best from all and put it as one Diagram.  Chirag's diagram explains the flow and we coud replace the cloud in this diagram from hrishikesh's diagram (it shows all main features of our app). Any suggestions?
