### ISSUE TITLE
Data models

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#20]
```js
export interface Album {
  id: string;
  name: string;
  description: string;
  size: number;
  createdDate: string;
  lastEditDate: string;
  owner: string;
  lastEditUser: string;
  access: string;
  collaborators: Array<User>;
  images: Array<Image>;
}
```

```js
export interface User {
  id: string;
  name: string;
  email: string;
  token: string;  
  photo: string;
}
```

```js
export interface Image {
  id: string
  name: string;
  image: string;
  createdDate: string;
  size: number;
  metaData: MetaData;
  modifiedDate: string;
  owner: string;
  extension: string
}

export interface MetaData {
  focalLength: string;
  iso: number;
  shutterSpeed: number;
  camera: string;
  location: string;
  colorSpace: string;
}
```

**Comment by jbhushan791** [comment]
Image data model:

export interface Image {
  id: string
  googleDriveId: string
  name: string;
  image: string;
  createdDate: string;
  size: number;
  metaData: MetaData;
  modifiedDate: string;
  owner: string;
  extension: string
}

**Comment by hrishikeshpaul** [comment]
@jbhushan791 what about the owner id and stuff? Will that be in a different database?

**Comment by jbhushan791** [comment]
@hrishikeshpaul : the upload api needs a user id (or email anything) which will be linked with the file. As there is user service already, image-service is not maintaing that in image database rather it would be maintained in separate database.

**Comment by hrishikeshpaul** [comment]
@jbhushan791 cool. could we have 2 different services doing this? We can have a "Google Drive Service" to handle the images (adding, edit, delete) and an "Image Service" that handles the User -> Image mapping. How does that sound?

**Comment by jbhushan791** [comment]
@hrishikeshpaul : Yes it sounds great, one responsibility per service. I will introduce another microservice naming scrapbook-googledrive-service.

**Comment by hrishikeshpaul** [comment]
@jbhushan791 isn't what you're doing right now (the current scrapbook-image-service) the  same as the scrapbook-google-drive-service?

**Comment by jbhushan791** [comment]
@hrishikeshpaul : in current i have included both drive as well as database for Image (Mongo). I will split this service into two.
