### ISSUE TITLE
Investigate and configure Google drive service in image-service

### ISSUE THREAD

**Issue by jbhushan791** [airavata-courses/scrapbook#4]
Create service account for scrapbook.
Configure google drive in image service i.e key, google drive library set up 

Google drive reference -
https://developers.google.com/drive/api/v3/about-sdk
https://developers.google.com/drive/api/v3/quickstart/java
https://developers.google.com/drive/api/v3/reference/files#resource
// model provided by google
https://googleapis.dev/java/google-api-services-drive/latest/index.html
https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority
https://cloud.google.com/iam/docs/understanding-service-accounts

**Comment by hrishikeshpaul** [comment]
Share some useful resources like blog or documentation so that we can touch base with it too!

**Comment by hrishikeshpaul** [comment]
@jbhushan791 what is the status on this?

**Comment by jbhushan791** [comment]
Created service account and required credential.  Google drive set up done. Tested upload api.

**Comment by jbhushan791** [comment]
> @jbhushan791 what is the status on this?

yes I completed on 12th. I encountered into mulitple issues while configuring google service. It took me sometime to research and resolve. Finally it is working. I tested the upoad service. Drive api is returning the id.

**Comment by jbhushan791** [comment]
Also i have used scrapbook.chk@gmail.com for creating service account.
