### ISSUE TITLE
Required API Routes for Image Service

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#61]
### Create an album

- route: `/album/<name>`
- type: POST
- take in the album name and userid
- create album
- return the created album (it will have no images)
- [x] Done

---

### Add image inside existing album

- route: `/album/image`
- Type: POST
- take userid, albumid
- return the created **image ID** back
- [x] Done

---

### Get all albums in the database

- route: `/albums?results=1` (same, get the first 20, then next 20 etc)
- type: GET
- desc: retrieve all albums in the database to show the user. Should return only name, description, size, createdBy, createdAt, modifiedBy, modifiedAt. Right now it is sending all the images, will be very hard to handle later. dont send the images. 
- [x] Done

---

### Get all Images for a particular album

- route: `/albums/images/<album_id>?results=1` (first 20. results = 2 will be next 20)
- type: GET
- desc: when the user clicks on an album this call is made. gets all the images for a particular album
- Try to see if you can return a thumbnail. otherwise just the basic data.
- [x] Done

---

 ### Get an image so that the user can see it

- route: `/image/<image_id>`
- type: GET
- desc: get an image as a stream of bytes to view on the frontend
- accepts: image_id, albumid
- [x] Done

**Comment by jbhushan791** [comment]
#### APIs:

### Create an album

(call image service, port : 8080 )

POST localhost:8080/album?userid=jyoti
_RequestBody:_ 
{
"name":<abumName>,
"description": <desc>
}
_QueryParam :_ 
"userid" : <userId>


### Add image inside existing album

(call googleDriveService PORT: 9090)

POST localhost:9090/image/upload/<albumGoogleDriveId>
_Path variable_ :  <albumGoogleDriveId>
_QueryParam :_ 
"userid" : <userId>
"file": <attach file>

### Get all albums in the database

(call imageService PORT: 8080)

Get all albums for given userId
GET localhost:8080/album?userid=jyoti
_QueryParam :_ 
"userid" : <userId>

Get all active albums
GET localhost:8080/all

### Get all Images for a particular album

(call imageService PORT: 8080)

GET localhost:8080/album/<albumGoogleId>/image?userid=jyoti
_QueryParam :_ 
"userid" : <userId>


### Get an image that user can see

(call googleDriveService PORT: 9090)

GET localhost:9090/image/<imageGoogleId>?userid=jyoti
_QueryParam :_ 
"userid" : <userId>
