### ISSUE TITLE
Finalize the architecture 

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#7]
Based on our meetings, I have created this diagram to consolidate the architecture. I'm not sure if this is full correct. I'm not sure where all do we need to use Kafka, and if certain services need to communicate with other services. Please comment below on what you think.

![Architecture](https://user-images.githubusercontent.com/22999894/106673875-561ea400-6580-11eb-8dfc-70c63b21e2e1.png)

@chirag-indi @jbhushan791

**Comment by chirag-indi** [comment]
I think it is mostly right, but the Imaging Service microservice would also have a database of its own that stores metadata about the images, such as path and owner attributes.

**Comment by hrishikeshpaul** [comment]
@chirag-indi yeah, you're right. I've updated the image above. I've also added an Indexing service. Let me know if this makes sense.

**Comment by jbhushan791** [comment]
Based on today's lecture, we need to redefine our architecture little bit. As one microservice is supposed to have database, lets include a new service may be call it as data-service responsible for all data like profiles, images etc. Other services would talk to this service for accessing data and eventually this data-service will become producer. Need to relocate Kafka for that.

**Comment by hrishikeshpaul** [comment]
@jbhushan791 what's the advantage of having the data-service? Is this sort of like a gateway but without authentication?
