### ISSUE TITLE
Delete Route for Images and Album

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#76]
Users should be able to delete images and albums. It shouldn't be "REMOVED" but active should be false. Also in mongo, there is a way to set the expiry date. Try to see if you can implement something that expired in 30 days if the status is inactive.

- route: `/image/<image_id>
- type: DELTE
- behavior: set active to false
- [x] DONE
---
- route: `/album/<ialbum_id>
- type: DELTE
- behavior: set active to false
- [x] DONE

**Comment by jbhushan791** [comment]
@hrishikeshpaul  : why do u want to expire the images? Is the plan to show deleted image in Trash on UI?

**Comment by hrishikeshpaul** [comment]
@jbhushan791 yes I thought that was the idea. That's why you also have an "active" variable right for the album. But if it's too difficult leave it. I'm fine with just deleting it or setting active to false. Your call!

**Comment by jbhushan791** [comment]
@hrishikeshpaul : I am setting is to inactive not deleting. But I thought of keeping all deleted stuffs too, just for auditing purpose.
And for trash API, I could just fetch those which were deleted with 30 days, not prior to that.

**Comment by jbhushan791** [comment]
Implemented these two APIs
