### ISSUE TITLE
As an user, I should be able to log in via my IU credentials 

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#8]
For this issue, find out how to use IU SSO. Post resources below in the comments

**Comment by chirag-indi** [comment]
The knowledge base article: https://kb.iu.edu/d/bdag 

The first step in the article asks us to fill the [SAML Integration Request form](https://ims-fireform.eas.iu.edu/online/form/authen/samlreg), but I am getting an access denied error. 

I will reach out to Bloomington's campus IT Support Center on 2nd Feb to request access to the form.

**Comment by hrishikeshpaul** [comment]
@chirag-indi  Cool, sounds great!
