### ISSUE TITLE
Add a private field to the album

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#84]
Add a field called `private` that can be true or false. This will cause the the album to not be visible when shared by URL to people who are not collaborators.

**Comment by jbhushan791** [comment]
@hrishikeshpaul : isn't better way is to query as per logged in user. fetch only those albums/images for which the logged user is either creator or collaborator. <like the way I had done earlier>

For example, when a logged in user tries to acess an album for which he is neither creator/collaborator, we will show empty folder with message indication missing rights or something.

**Comment by hrishikeshpaul** [comment]
@jbhushan791 Sorry I'm just seeing this now. I think that is also a way to implement it. Having a private/public field would just be easier on your end. But yeah, whatever works. As long as the correct data is shown, thats okay
